// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Count = (function(_super) {
    __extends(Count, _super);

    function Count() {
      _ref = Count.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Count.prototype.initialize = function() {
      this.destroy();
      this.scene = this.get('scene');
      this.camera = this.get('camera');
      this.on('change:shown', function(model, value, obj) {
        return model.trigger({
          "true": 'show',
          "false": 'hide'
        }[value], model);
      });
      this.on('show', function(model) {
        var mesh;
        if (!(mesh = model.get('mesh'))) {
          mesh = model._generateMesh();
          model.set({
            mesh: mesh
          });
        }
        if (model.scene && mesh) {
          return model.scene.add(mesh);
        }
      });
      this.on('show', function(model) {
        var randY, randZ;
        model.sourceRotationY = model.sourceRotationZ = Math.PI * 0.5;
        model.deltaRotationY = model.deltaRotationZ = Math.PI * -0.5;
        randY = Math.random() > 0.5;
        if ((model.get('text') + '') === '1' || (model.get('text') + '') === '7') {
          randZ = randY;
        } else {
          randZ = Math.random() > 0.5;
        }
        if (randY > 0.5) {
          model.sourceRotationY = model.sourceRotationY * -1;
          model.deltaRotationY = model.deltaRotationY * -1;
        }
        if (randZ > 0.5) {
          model.sourceRotationZ = model.sourceRotationZ * -1;
          model.deltaRotationZ = model.deltaRotationZ * -1;
        }
        model.sourceScale = 5;
        return model.deltaScale = 1 - model.sourceScale;
      });
      this.on('change:mesh', function(model, value, obj) {
        if (model.scene) {
          if (model.previous('mesh')) {
            return model.scene.remove(model.previous('mesh'));
          }
        }
      });
      this.on('hide', function(model) {
        var m;
        if (model.scene && (m = model.get('mesh'))) {
          model.scene.remove(m);
        }
        return model.randomizeColor();
      });
      this.on('change:color', function(model, value, obj) {
        var m;
        if (m = model.get('mesh') && model.get('mesh').material) {
          return model.get('mesh').material.color = value;
        }
      });
      if (this.get('shown') === void 0) {
        return this.hide();
      }
    };

    Count.prototype.destroy = function() {
      this.trigger('destroy');
      this.hide;
      this.scene = this.camera = void 0;
      return Count.__super__.destroy.call(this);
    };

    Count.prototype._generateGeometry = function() {
      var geometry;
      geometry = new THREE.TextGeometry('' + (this.get('text') || 0), {
        size: 40,
        height: 5,
        curveSegments: 30,
        font: "helvetiker",
        weight: "bold",
        style: "normal",
        bevelSize: 1,
        bevelEnabled: true
      });
      THREE.GeometryUtils.center(geometry);
      return geometry;
    };

    Count.prototype._generateMaterial = function() {
      return new THREE.MeshBasicMaterial({
        color: this.getColor()
      });
    };

    Count.prototype._generateMesh = function() {
      var mesh;
      mesh = new THREE.Mesh(this.geometry || this._generateGeometry(), this.material || this._generateMaterial());
      mesh.position.x = 0;
      mesh.position.y = 0;
      mesh.position.z = this.camera.position.z - 120;
      return mesh;
    };

    Count.prototype._defaultColor = function() {
      return new THREE.Color(255, 0, 0);
    };

    Count.prototype.randomizeColor = function() {
      var clr, hsl, mesh;
      if (this.get('color')) {
        clr = this.get('color').clone();
      }
      if (mesh = this.get('mesh')) {
        clr || (clr = mesh.material.color);
      }
      clr || (clr = this._defaultColor());
      hsl = clr.getHSL();
      clr.setHSL(Math.random(), hsl.s, hsl.l);
      return this.set({
        color: clr
      });
    };

    Count.prototype.getColor = function() {
      return this.get('color') || this._defaultColor();
    };

    Count.prototype.hide = function() {
      return this.set({
        shown: false
      });
    };

    Count.prototype.show = function(progress) {
      var mesh, p, ry, rz, s;
      this.set({
        shown: true
      });
      if (!(mesh = this.get('mesh'))) {
        return;
      }
      if (progress < 0.1 || progress > 0.9) {
        p = progress;
        ry = this.sourceRotationY;
        rz = this.sourceRotationZ;
        s = this.sourceScale;
      } else {
        p = (progress - 0.1) / 0.8;
        ry = this.sourceRotationY + Math.sin(p * Math.PI) * this.deltaRotationY;
        rz = this.sourceRotationZ + Math.sin(p * Math.PI) * this.deltaRotationZ;
        s = this.sourceScale + Math.sin(p * Math.PI) * this.deltaScale;
      }
      mesh.rotation.y = ry;
      mesh.rotation.z = rz;
      return mesh.scale = new THREE.Vector3(s, s, s);
    };

    return Count;

  })(Backbone.Model);

}).call(this);
