// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Counter = (function(_super) {
    __extends(Counter, _super);

    function Counter() {
      _ref = Counter.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Counter.prototype.initialize = function() {
      var count_ops_array,
        _this = this;
      this.amount = 10;
      count_ops_array = _.map(_.range(this.amount), function(number, idx, list) {
        var count, count_op;
        count = new Count({
          scene: _this.get('scene'),
          camera: _this.get('camera'),
          text: number
        });
        return count_op = new CountOps({
          target: count
        });
      });
      this.count_ops = new Backbone.Collection(count_ops_array);
      this.on('change:progress', function(model, value, obj) {
        model.set({
          idx: this.calcIndex()
        });
        return model.currentOp().fall((value - model.countLength() * model.get('idx')) / model.countLength());
      });
      return this.on('change:idx', function(model, value, obj) {
        return model.count_ops.each(function(op, i) {
          if (i !== value) {
            return op.hide();
          }
        });
      });
    };

    Counter.prototype.update = function(progress) {
      return this.set({
        progress: progress
      });
    };

    Counter.prototype.countLength = function() {
      return 1.0 / this.amount;
    };

    Counter.prototype.calcIndex = function() {
      var idx;
      return idx = parseInt(this.get('progress') * this.amount);
    };

    Counter.prototype.nextIndex = function() {
      var idx;
      idx = (this.get('idx') || this.calcIndex()) + 1;
      if (idx >= this.amount) {
        idx = 0;
      }
      return idx;
    };

    Counter.prototype.currentOp = function() {
      return this.count_ops.at(this.get('idx')) || this.count_ops.at(this.get('idx') - 1);
    };

    Counter.prototype.nextOp = function() {
      return this.count_ops.at(this.nextIndex()) || this.count_ops.at(this.nextIndex() - 1);
    };

    Counter.prototype.currentColor = function() {
      return this.currentOp().get('target').getColor();
    };

    Counter.prototype.nextColor = function() {
      return this.nextOp().get('target').getColor();
    };

    return Counter;

  })(Backbone.Model);

}).call(this);
