// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.PostProcessor = (function(_super) {
    __extends(PostProcessor, _super);

    function PostProcessor(_opts) {
      this.options = _opts || {};
      this.init();
    }

    PostProcessor.prototype.init = function() {
      this.destroy();
      this.renderer = this.options.renderer;
      this.scene = this.options.scene;
      this.camera = this.options.camera;
      this.composer = new THREE.EffectComposer(this.renderer);
      this.composer.addPass(new THREE.RenderPass(this.scene, this.camera));
      this.blindsEffect = new THREE.ShaderPass(THREE.BlindsShader);
      this.blindsEffect.renderToScreen = true;
      this.composer.addPass(this.blindsEffect);
      return this.on('update', function(model, opts) {
        return model.blindsEffect.uniforms.progress.value = (opts || {}).blindsProgress || 0.0;
      });
    };

    PostProcessor.prototype.destroy = function() {
      this.trigger('destroy');
      if (this.composer) {
        this.composer = void 0;
      }
      return this.dotScreenEffect = this.rgbShiftEffect = this.scene = this.camera = void 0;
    };

    PostProcessor.prototype.update = function(opts) {
      this.frame || (this.frame = 0);
      this.trigger('update', this, opts);
      return this.frame += 0.05;
    };

    return PostProcessor;

  })(Backbone.Model);

}).call(this);
